import { HTTPFacilitatorClient } from "@x402/core/server";
import { paymentMiddleware, x402ResourceServer } from "@x402/hono";
import { ExactSvmScheme } from "@x402/svm/exact/server";
import type { MiddlewareHandler } from "hono";
import type { AgentApiConfig } from "./config.js";

export function createReflectionPayment(
  config: AgentApiConfig,
  syncFacilitatorOnStart = true,
): MiddlewareHandler {
  const facilitator = new HTTPFacilitatorClient({ url: config.facilitatorUrl });
  const resourceServer = new x402ResourceServer(facilitator).register(
    config.network,
    new ExactSvmScheme(),
  );

  return paymentMiddleware(
    {
      "POST /v1/reflection": {
        accepts: {
          scheme: "exact",
          network: config.network,
          payTo: config.payTo,
          price: config.price,
        },
        description: "Roselet AI reflection generated by the shared Rust recommendation engine",
        mimeType: "application/json",
      },
    },
    resourceServer,
    undefined,
    undefined,
    syncFacilitatorOnStart,
  );
}
